feat: shape our TF module scaffolding
lacework/terraform-module-scaffolding pull request #1
Opened 2021-04-21 23:27 UTC by afiune

This PR is shaping how our Terraform Module Scaffolding will look like! 🙌🏽

The idea of this repository is to have an easy way to create new Terraform Modules
for anyone at Lacework.
 
Signed-off-by: Salim Afiune Maya <afiune@lacework.net>

2021-04-21 23:33 UTC, scottford-lw approved these changes
![](https://media4.giphy.com/media/3oeSAD00YsGzUPTmqA/giphy.gif)

2021-04-21 23:48 UTC, afiune commented
I found this document that explains how to mirror a repo https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

Though we can't because we have branch protection
```
➜  terraform-module-scaffolding git:(afiune/scaffolding) git push --mirror  https://github.com/lacework/terraform-aws-ecs-agent.git
Enumerating objects: 25, done.
Counting objects: 100% (25/25), done.
Delta compression using up to 12 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (25/25), 8.29 KiB | 2.76 MiB/s, done.
Total 25 (delta 1), reused 3 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Cannot force-push to this protected branch
To ssh://github.com/lacework/terraform-aws-ecs-agent.git
 - [deleted]         alannix-lw/initial
 * [new branch]      afiune/scaffolding -> afiune/scaffolding
 * [new branch]      origin/HEAD -> origin/HEAD
 * [new branch]      origin/afiune/scaffolding -> origin/afiune/scaffolding
 * [new branch]      origin/main -> origin/main
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'ssh://git@github.com/lacework/terraform-aws-ecs-agent.git'
```

2021-04-21 23:49 UTC, afiune commented
Also, I messed up https://github.com/lacework/terraform-aws-ecs-agent/pull/1 🤦🏽‍♂️ - Apologies @alannix-lw 😅

2021-04-22 00:07 UTC, afiune commented
This looks much better: 

https://github.com/lacework/terraform-aws-ecs-agent/pull/2

![tenor-136445774](https://user-images.githubusercontent.com/5712253/115637015-7848d800-a2cc-11eb-91ff-d1e59ad94087.gif)

2021-04-22 18:02 UTC, scottford-lw approved these changes
👍

2021-04-22 18:27 UTC, alannix-lw requested changes

2021-04-22 18:27 UTC, alannix-lw commented on examples/default/README.md
> +  source  = "lacework/<PROVIDER>/<NAME>"
```suggestion
  source  = "lacework/<NAME>/<PROVIDER>"
```

2021-04-27 23:09 UTC, afiune commented on scripts/release_helpers.sh
> +  git config --global user.email $git_email
```suggestion
  git config --global user.email $git_email
```

2021-04-27 23:09 UTC, afiune commented on scripts/release_helpers.sh
> +    git config --global user.email $git_email
```suggestion
    git config --global user.email $git_email
```

2021-04-27 23:12 UTC, merged